### ISSUE TITLE
在线访问的账号、密码是多少？

### ISSUE THREAD

**Issue by dirk88** [youngon-cn/vod-admin#1]

**Comment by F-loat** [comment]
这个项目暂时是使用我们学校的账号体系，有需要的话你可以把 [vod-server](https://github.com/youngon-cn/vod-server) 这个项目 clone 到本地，然后自行修改一下 `controllers/user.js` 中的 `login` 函数，

过段时间会再维护这几个项目，可能加入独立的注册登录，然后搭在一个测试服务器上

**Comment by F-loat** [comment]
该仓库将废弃并删除，原有内容已合并至 [vod-client](https://github.com/youngon-cn/vod-client) 的 `muse-ui` 分支，并不再维护，主分支改用 [Quasar](http://quasar-framework.org/) 作为UI框架
